fastDev.apply(fastDev.Ui.DataGrid, {
	setTemplate : function(global) {
		this.template = [
			'<div class="ui-datagrid" style="width: #{width}px;">', 
				'<div class="ui-datagrid-panel ui-datagrid-box" style="width:#{bodyWidth}px;">', 
					'<div name="ui-top-toolbar"></div><div style="display:none"></div>', 
					'<div class="ui-datagrid-header" style="width: #{bodyWidth}px; ">', 
						'<div name="header">', 
							'<tpl dynamic name=header>', 
								'<table class="ui-datagrid-table" cellspacing="0" cellpadding="0">', 
									'<tbody>', 
										'<tr name="colwidthlimit">',
											'#{colWidthTpl}',
										'</tr>', 
										'#{colTitleTpl}', 
									'</tbody>', 
								'</table>', 
							'</tpl>', 
						'</div>', 
						'<div class="ui-datagrid-splitters">',
							global.colSplitTpl, 
						'</div>', 
					'</div>', 
					'<div class="ui-datagrid-body" style="width: #{bodyWidth}px;height:100% ">', 
						'<tpl dynamic name=body>', 
							'<table class="ui-datagrid-table" cellspacing="0" cellpadding="0">', 
								'<tbody>', 
									'<tr name="colwidthlimit">',
										'#{colWidthTpl}',
									'</tr>', 
									'<tpl each>', 
										'<tr class="ui-datagrid-row', 
											'<tpl if( rowid % 2 === 0)>', 
												' ui-datagrid-row-alt', 
											'</tpl>', 
											'">',
											global.colContentTpl, 
										'</tr>', 
										'<tpl if(#{buildRowDetail})>', 
											'<tr style="display:none"><td class="ui-datagrid-cell" colSpan="#{colspan}"><div class="ui-datagrid-cell-content"></div></td></tr>', 
										'</tpl>', 
									'</tpl>', 
								'</tbody>', 
							'</table>', 
						'</tpl>', 
					'</div>', 
					'<div class="ui-datagrid-count" style="width: #{bodyWidth}px; display:none"></div>', 
					'<div name="ui-bottom-toolbar"></div>', 
				'</div>', 
			'</div>'
		];
	}
});
